-- MySQL Script generated by MySQL Workbench
-- Thu May 30 17:55:07 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mundofesteirobd2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mundofesteirobd2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mundofesteirobd2` ;
USE `mundofesteirobd2` ;

-- -----------------------------------------------------
-- Table `mundofesteirobd2`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundofesteirobd2`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `contactno` BIGINT NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `shippingAddress` LONGTEXT NULL DEFAULT NULL,
  `shippingState` VARCHAR(255) NULL DEFAULT NULL,
  `shippingCity` VARCHAR(255) NULL DEFAULT NULL,
  `shippingPincode` INT NULL DEFAULT NULL,
  `Status` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundofesteirobd2`.`localidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundofesteirobd2`.`localidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `endereco` VARCHAR(255) NOT NULL,
  `bairro` VARCHAR(255) NOT NULL,
  `cidade` VARCHAR(255) NOT NULL,
  `estado` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundofesteirobd2`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundofesteirobd2`.`evento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `localidade_id` INT NOT NULL,
  `nomeEvento` VARCHAR(255) NOT NULL,
  `tipoEvento` VARCHAR(255) NOT NULL,
  `data` DATETIME NOT NULL,
  `quantidadePessoas` INT NOT NULL,
  `quantidadeFuncionarios` INT NOT NULL,
  `statusEvento` VARCHAR(255) NOT NULL,
  `descricaoEvento` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_evento_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_evento_localidade1_idx` (`localidade_id` ASC) VISIBLE,
  CONSTRAINT `fk_evento_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mundofesteirobd2`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_localidade1`
    FOREIGN KEY (`localidade_id`)
    REFERENCES `mundofesteirobd2`.`localidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundofesteirobd2`.`imgevento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundofesteirobd2`.`imgevento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `evento_id` INT NOT NULL,
  `img` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_imgevento_evento_idx` (`evento_id` ASC) VISIBLE,
  CONSTRAINT `fk_imgevento_evento`
    FOREIGN KEY (`evento_id`)
    REFERENCES `mundofesteirobd2`.`evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundofesteirobd2`.`avatar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundofesteirobd2`.`avatar` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `avatar` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_avatar_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_avatar_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mundofesteirobd2`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundofesteirobd2`.`prestador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundofesteirobd2`.`prestador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `localidade_id` INT NOT NULL,
  `promotorEvento` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `curriculo` LONGTEXT NOT NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_prestador_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_prestador_localidade1_idx` (`localidade_id` ASC) VISIBLE,
  CONSTRAINT `fk_prestador_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mundofesteirobd2`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prestador_localidade1`
    FOREIGN KEY (`localidade_id`)
    REFERENCES `mundofesteirobd2`.`localidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundofesteirobd2`.`userlog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundofesteirobd2`.`userlog` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `userEmail` VARCHAR(255) NULL DEFAULT NULL,
  `userip` BINARY(16) NULL DEFAULT NULL,
  `loginTime` DATETIME NULL DEFAULT NULL,
  `logout` VARCHAR(255) NULL DEFAULT NULL,
  `status` INT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_userlog_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_userlog_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mundofesteirobd2`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundofesteirobd2`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundofesteirobd2`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `categoryName` VARCHAR(255) NULL DEFAULT NULL,
  `categoryDescription` LONGTEXT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundofesteirobd2`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundofesteirobd2`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `productName` VARCHAR(255) NULL DEFAULT NULL,
  `productCompany` VARCHAR(255) NULL DEFAULT NULL,
  `productPrice` FLOAT NULL DEFAULT NULL,
  `productPriceBeforeDiscount` FLOAT NULL DEFAULT NULL,
  `productDescription` LONGTEXT NULL DEFAULT NULL,
  `productImage1` VARCHAR(255) NULL DEFAULT NULL,
  `productImage2` VARCHAR(255) NULL DEFAULT NULL,
  `productImage3` VARCHAR(255) NULL DEFAULT NULL,
  `shippingCharge` INT NULL DEFAULT NULL,
  `Status` BIT(1) NULL DEFAULT b'0',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_products_category1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `mundofesteirobd2`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundofesteirobd2`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundofesteirobd2`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `products_id` INT NOT NULL,
  `quantity` INT NULL DEFAULT NULL,
  `paymentMethod` VARCHAR(50) NULL DEFAULT NULL,
  `orderStatus` VARCHAR(55) NULL DEFAULT NULL,
  `ValorAPagar` FLOAT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_orders_products1_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mundofesteirobd2`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `mundofesteirobd2`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundofesteirobd2`.`ordertrackhistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundofesteirobd2`.`ordertrackhistory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `orders_id` INT NOT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  `remark` VARCHAR(255) NULL DEFAULT NULL,
  `postingDate` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_ordertrackhistory_orders1_idx` (`orders_id` ASC) VISIBLE,
  CONSTRAINT `fk_ordertrackhistory_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `mundofesteirobd2`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundofesteirobd2`.`wishlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundofesteirobd2`.`wishlist` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `products_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_wishlist_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_wishlist_products1_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_wishlist_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mundofesteirobd2`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wishlist_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `mundofesteirobd2`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundofesteirobd2`.`subcategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundofesteirobd2`.`subcategory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `subcategory` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_subcategory_category1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_subcategory_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `mundofesteirobd2`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundofesteirobd2`.`profissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundofesteirobd2`.`profissao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `profissao` VARCHAR(255) NOT NULL,
  `iconURL` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundofesteirobd2`.`timestamps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundofesteirobd2`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);


-- -----------------------------------------------------
-- Table `mundofesteirobd2`.`prestador_has_evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundofesteirobd2`.`prestador_has_evento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `prestador_id` INT NOT NULL,
  `evento_id` INT NOT NULL,
  `aceitarPrestador` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`, `prestador_id`, `evento_id`),
  INDEX `fk_prestador_has_evento_evento1_idx` (`evento_id` ASC) VISIBLE,
  INDEX `fk_prestador_has_evento_prestador1_idx` (`prestador_id` ASC) VISIBLE,
  CONSTRAINT `fk_prestador_has_evento_prestador1`
    FOREIGN KEY (`prestador_id`)
    REFERENCES `mundofesteirobd2`.`prestador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prestador_has_evento_evento1`
    FOREIGN KEY (`evento_id`)
    REFERENCES `mundofesteirobd2`.`evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundofesteirobd2`.`prestador_has_profissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundofesteirobd2`.`prestador_has_profissao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `prestador_id` INT NOT NULL,
  `profissao_id` INT NOT NULL,
  `tempoexperiencia` INT NOT NULL,
  `valorDiaServicoProfissao` FLOAT NOT NULL,
  `valorHoraServicoProfissao` FLOAT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`, `prestador_id`, `profissao_id`),
  INDEX `fk_prestador_has_profissao_profissao1_idx` (`profissao_id` ASC) VISIBLE,
  INDEX `fk_prestador_has_profissao_prestador1_idx` (`prestador_id` ASC) VISIBLE,
  CONSTRAINT `fk_prestador_has_profissao_prestador1`
    FOREIGN KEY (`prestador_id`)
    REFERENCES `mundofesteirobd2`.`prestador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prestador_has_profissao_profissao1`
    FOREIGN KEY (`profissao_id`)
    REFERENCES `mundofesteirobd2`.`profissao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundofesteirobd2`.`evento_has_profissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundofesteirobd2`.`evento_has_profissao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `evento_id` INT NOT NULL,
  `profissao_id` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`, `evento_id`, `profissao_id`),
  INDEX `fk_evento_has_profissao_profissao1_idx` (`profissao_id` ASC) VISIBLE,
  INDEX `fk_evento_has_profissao_evento1_idx` (`evento_id` ASC) VISIBLE,
  CONSTRAINT `fk_evento_has_profissao_evento1`
    FOREIGN KEY (`evento_id`)
    REFERENCES `mundofesteirobd2`.`evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_has_profissao_profissao1`
    FOREIGN KEY (`profissao_id`)
    REFERENCES `mundofesteirobd2`.`profissao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundofesteirobd2`.`contrar_prestador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundofesteirobd2`.`contrar_prestador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `aceitarProposta` INT NOT NULL DEFAULT 0,
  `prestador_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `updated_at` VARCHAR(45) NULL DEFAULT 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
  `created_at` VARCHAR(45) NULL DEFAULT 'CURRENT_TIMESTAMP',
  PRIMARY KEY (`id`, `prestador_id`, `users_id`),
  INDEX `fk_contrar_prestador_prestador1_idx` (`prestador_id` ASC) VISIBLE,
  INDEX `fk_contrar_prestador_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_contrar_prestador_prestador1`
    FOREIGN KEY (`prestador_id`)
    REFERENCES `mundofesteirobd2`.`prestador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contrar_prestador_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mundofesteirobd2`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
