INSERT INTO categorias (categoria) VALUES
('Balões'),
('Velas de Aniversário'),
('Decorações de Mesa'),
('Copos e Talheres Descartáveis'),
('Pratos Descartáveis'),
('Toalhas de Mesa'),
('Guardanapos'),
('Chapéus de Festa'),
('Convites'),
('Sacolas de Lembrancinhas'),
('Caixas de Lembrancinhas'),
('Confetes'),
('Acessórios para Fantasias'),
('Fantasia Infantil'),
('Fantasia Adulto'),
('Máscaras'),
('Decoração de Teto'),
('Cortinas Decorativas'),
('Papel de Parede Temático'),
('Balões de Número'),
('Balões de Letra'),
('Balões Metalizados'),
('Balões Personalizados'),
('Suportes para Bolos e Doces'),
('Topo de Bolo'),
('Cupcake Wrappers'),
('Etiquetas e Adesivos'),
('Bandejas Decorativas'),
('Forminhas para Doces'),
('Painéis Decorativos'),
('Faixas de Feliz Aniversário'),
('Chaveiros e Ímãs'),
('Pulseiras e Colares Luminosos'),
('Luzes Decorativas'),
('Tiaras e Coroas'),
('Flores Artificiais'),
('Baldes de Pipoca'),
('Lanternas Decorativas'),
('Papel Picado'),
('Plaquinhas de Fotos'),
('Bexigas de Gás Hélio'),
('Enfeites para Bolo'),
('Canudos Decorativos'),
('Papel de Seda para Decoração'),
('Personagens Temáticos'),
('Chocolates Personalizados'),
('Brindes Personalizados'),
('Kit Festa Completo'),
('Adereços para Photobooth'),
('Lembrancinhas comestíveis');